export { DesktopApp } from './DesktopApp'
export { GlobalNotifications } from './components/GlobalNotifications'
export { LoadingOverlay } from './components/LoadingOverlay'
export { ErrorBoundary } from './components/ErrorBoundary'
export { Dashboard } from './pages/Dashboard'
export { RecentProjects } from './pages/RecentProjects'
export { SettingsPage } from './pages/SettingsPage'
export { useDesktopStore } from './store/DesktopStore'
export { useSettingsStore } from './store/SettingsStore'
export { NavigationRouter, useNavigation } from './services/NavigationRouter'
export type { SessionState, NotificationState, LoadingState, ErrorBoundaryState } from './types/desktop'
